### ISSUE TITLE
Support for custom pages in rss

### ISSUE THREAD

**Issue by ericdallo** [Guts/mkdocs-rss-plugin#11]
Is it possible to add a option to specify which folders I want to add to rss XML?
```yaml
plugins:
  - rss:
    path: ["/tutorials", "/blog"]
```

Thanks!
