### ISSUE TITLE
Date shifted by timezone when using `date_from_meta`

### ISSUE THREAD

**Issue by squidfunk** [Guts/mkdocs-rss-plugin#133]
First of all, great plugin! Material for MkDocs will get blog support tomorrow, and I'm finishing up the last small little details to make it awesome. Your plugin will be advertised on the documentation for adding RSS support, as it's the best one out there.

I've encountered a problem where the dates of blog articles are not correctly computed when `date_from_meta` is used. my configuration in `mkdocs.yml` is as follows:

``` yaml
plugins:
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
```

When I set a date in a blog article, the computed time is shifted by the UTC offset of the current timezone. For example:

```
---
date: 2022-05-05
---
```

Becomes:

``` xml
<pubDate>Wed, 04 May 2022 22:00:00 -0000</pubDate>
```

IMHO, dates should be treated as UTC. I'm currently in UTC+2, so this seems to be the problem.
