### ISSUE TITLE
RSS plugin is throwing error with mkdocs-material blog

### ISSUE THREAD

**Issue by zerenxyz** [Guts/mkdocs-rss-plugin#161]
When I run the link via a RSS Validator and I get an error for the author name:

```
line 1, column 433: Invalid email address: zeren [help]

... Hello again world!</title> <author>zeren</author> <category>Bar</categor ...
```

and also description error like this:

```line
line 1, column 676: Missing channel element: description [help]
... n 2022 00:00:00 +0000</pubDate> </item> </channel></rss>
```

---

My mkdocs.yml file:
```
site_name: My Docs
theme:
  name: material

plugins:
  - blog:
      enabled: true
      blog_dir: blog/
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

nav:
  - Blog:
    - blog/index.md
```

Example the a post:
```
---
draft: false
date: 2022-01-31
categories:
    - General
tags:
  - Foo
  - Bar
authors:
  - "zeren"
---

# Hello again world!


Helloooo!
```

my .author.yml file in blog/
```
zeren:
  name: zeren
  description: Testing
  avatar: http://placekitten.com/300/300
```

Direct link to github pages test: https://zerenxyz.github.io/testing-mkdocs/blog/
