### ISSUE TITLE
match_path issues

### ISSUE THREAD

**Issue by carried-away** [Guts/mkdocs-rss-plugin#264]
Hello,

My blog doesn't use the default 'blog' value. I have the folder named 'my-news'

```
docs/
   my-news/
      posts/
```

in my mkdocs.yml

```
 - blog:
      blog_dir: my-news
  - rss:
      abstract_chars_count: 150
      match_path: my-news/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
```

I only get matches if i do 
`match_path: my-news
`

But that matches the Archive and Category folders and I get double posts.

I'm not exactly sure where I'm going wrong here

**Comment by shenweiyan** [comment]
Do we need to add a `post_dir` setting in the blog configuration, like the example below?

```
- blog:
    blog_dir: my-news
    post_dir: "{blog}/posts"
- rss:
    abstract_chars_count: 150
    match_path: my-news/posts/.*
```
